// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RhommieBank.Services.MasterAPI.Data;

#nullable disable

namespace RhommieBank.Services.MasterAPI.Migrations
{
    [DbContext(typeof(RhommieBankDbContext))]
    [Migration("20231104053005_SeedingPerson")]
    partial class SeedingPerson
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RhommieBank.Services.PersonAPI.Models.Person", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_dt")
                        .HasColumnType("datetime2");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            id = 1,
                            age = 22,
                            created_by = "System",
                            created_dt = new DateTime(2023, 11, 4, 12, 30, 5, 592, DateTimeKind.Local).AddTicks(7416),
                            name = "Erling Haaland"
                        },
                        new
                        {
                            id = 2,
                            age = 24,
                            created_by = "System",
                            created_dt = new DateTime(2023, 11, 4, 12, 30, 5, 592, DateTimeKind.Local).AddTicks(7444),
                            name = "Kylian Mbappe"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
