// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RhommieBank.Services.PersonAPI.Data;

#nullable disable

namespace RhommieBank.Services.PersonAPI.Migrations
{
    [DbContext(typeof(RhommieBankDbContext))]
    [Migration("20231104134027_CreateTable_Bank")]
    partial class CreateTable_Bank
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RhommieBank.Services.PersonAPI.Models.Bank", b =>
                {
                    b.Property<string>("BankCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BankCode");

                    b.ToTable("Bank");

                    b.HasData(
                        new
                        {
                            BankCode = "014",
                            BankName = "BCA"
                        },
                        new
                        {
                            BankCode = "002",
                            BankName = "BRI"
                        },
                        new
                        {
                            BankCode = "008",
                            BankName = "Bank Mandiri"
                        },
                        new
                        {
                            BankCode = "009",
                            BankName = "BNI"
                        });
                });

            modelBuilder.Entity("RhommieBank.Services.PersonAPI.Models.Person", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_dt")
                        .HasColumnType("datetime2");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            id = 1,
                            age = 22,
                            created_by = "System",
                            created_dt = new DateTime(2023, 11, 4, 20, 40, 27, 246, DateTimeKind.Local).AddTicks(8508),
                            name = "Erling Haaland"
                        },
                        new
                        {
                            id = 2,
                            age = 24,
                            created_by = "System",
                            created_dt = new DateTime(2023, 11, 4, 20, 40, 27, 246, DateTimeKind.Local).AddTicks(8543),
                            name = "Kylian Mbappe"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
